name: Daily Check-in

on:
  schedule:
    - cron: '*/30 21-23 * * *'  # 每天 21 点到 23 点每小时执行一次
    - cron: '*/30 0-9 * * *'    # 每天 0 点到 9 点每小时执行一次
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install firefox

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python main.py
